# Generated by Django 5.1.5 on 2025-02-04 14:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('water_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tds', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_api.hydroponicsystem')),
            ],
        ),
    ]
